apiVersion: v1
kind: Service
metadata:
  name: swagger-gateway
  labels:
    app: swagger-gateway
spec:
  selector:
    app: swagger-gateway
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 80
      targetPort: 9999
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    #nginx.ingress.kubernetes.io/secure-backends: "true"
    #nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
    #nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
    nginx.ingress.kubernetes.io/rewrite-target: /$2
  name: ingress-swagger-ui
  namespace: pilot
spec:
  ingressClassName: nginx
  rules:
   - http:
      paths:
      - path: /swagger
        pathType: Prefix
        backend:
          service:
            name: swagger-gateway
            port:
              number: 80
