podTemplate(label: 'docker-build', 
  containers: [
    containerTemplate(
      name: 'git',
      image: 'alpine/git',
      command: 'cat',
      ttyEnabled: true
    ),
    containerTemplate(
      name: 'docker',
      image: 'docker',
      command: 'cat',
      ttyEnabled: true
    ),
  ],
  volumes: [ 
    hostPathVolume(mountPath: '/var/run/docker.sock', hostPath: '/var/run/docker.sock'), 
  ]
) {
    node('docker-build') {
        def now = java.time.LocalDateTime.now()
        def projectId = "openapi-common-ui" // 프로젝트 아이디

        // docker
        def dockerhubCredentialsId = "doldoleo" // 젠킨스 도커허브 자격증명
        def dockerImage = "${dockerhubCredentialsId}/${projectId}" // 도커허브 이미지
        def dockerImageTag = "latest" // 도커허브 이미지 태그

        stage('Checkout'){
            container('git'){
                checkout scm
            }
        }
        
        stage("gradle") {
            sh "./gradlew wrap --gradle-version=7.3 --daemon"
            sh "./gradlew bootJar"
        }
    
        stage("buildImage") {
            container("docker") {
                withCredentials([usernamePassword(credentialsId: "${dockerhubCredentialsId}", passwordVariable: "password", usernameVariable: "username")]) {
                    sh "docker login -u $username -p $password"
                    sh "docker build -f DockerfileK8s -t ${dockerImage}:${dockerImageTag} ."
                    sh "docker push ${dockerImage}:${dockerImageTag}"
                }
            }
        }

    }
}