server:
  port: 9000

spring:
  application:
    name: spring-cloud-gateway #MSA에서 해당 서비스를 구별할 수 있는 고유한 ID
  profiles:
      active: local 

management:
  endpoints:
    web:
      exposure:
        include: "*"
          
  endpoint:
    gateway:
      enabled: true  # default: true     
      
  tracing:
    sampling:
      probability: 1.0
    propagation:
      consume: B3
      produce: B3_MULTI
    enabled: true
  zipkin:
    tracing:
       endpoint: http://192.168.0.101:30411/api/v2/spans      
