spring:
  config:
    activate:
      on-profile: dev 

  #oauth2 서버 리소스 서버 설정
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://auth.5finger.co.kr:9000
                
  #gateway setting    
  cloud:
    gateway:
      default-filters: # 전역 필터 설정 (모든 라우터 목록들에 대해서 해당 필터 적용)
        - name : GlobalFilter #전역 필터 클래스 이름
          args: #  필터에 전달되는 추가 인수 설정
            baseMessage : Spring Cloud Gateway GlobalFilter
            preLogger : true
            postLogger : true
      routes: #라우팅 규칙 목록 설정
        - id : payment-service
          uri:  http://payment-service.pilot # 
          predicates:
            - Path=/api/v1/payment/**
            - Method=GET,POST,PUT,DELETE,OPTIONS
          filters:
            - AddRequestHeader=first-request, first-request-header2 #요청 헤더 추가 필터 적용
            - AddResponseHeader=first-response, first-response-header2 #응답 헤더 추가 필터 적용
            - CustomFilter 
        - id : user-service
          uri: http://user-service.pilot 
          predicates:
            - Path=/api/v1/user/**
          filters:
            - CustomFilter
        - id : feign-service
          uri: http://feign-service.pilot 
          predicates:
            - Path=/api/v1/merge/**
          filters:
            - CustomFilter         