apiVersion: apps/v1
kind: Deployment
metadata:
  name: eureka
  namespace: pilot
  labels:
    app: eureka
spec:
  replicas: 3
  selector:
    matchLabels:
      app: eureka
  template:
    metadata:
      labels:
        app: eureka
    spec:
      containers:
      - name: eureka
        image: doldoleo/eureka:latest
        ports:
        - containerPort: 8761

