---
apiVersion: v1
kind: Service
metadata:
  name: eureka
  namespace: pilot
  labels:
    app: eureka
spec:
  selector:
    app: eureka
  type: NodePort
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8761
      nodePort: 31815

