apiVersion: v1
kind: Service
metadata:
  name: payment-service
  labels:
    app: payment-service
spec:
  selector:
    app: payment-service
  type: NodePort
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8081
      nodePort: 30500
