server:
  port: 9002
  
spring:
  application:
     name: scg-ui
  
  # yaml/yml 파일 - Thymeleaf 설정
  thymeleaf:
    cache: false
    check-template-location: true #파일의 존재 여부 확인
    prefix: classpath:/templates/ #파일의 시작위치
    suffix: .html #파일의 확장자명
    enabled: true   
    #view-names: /pages/*  
  web:
     resources:
        static-locations: classpath:/static/  
   
  profiles:
    include: oauth
    
api:
  gateway:
     url: http://gateway.5finger.co.kr:30060
