apiVersion: v1
kind: Service
metadata:
  name: logger-service
  labels:
    app: logger-service
spec:
  selector:
    app: logger-service
  type: NodePort
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
      nodePort: 32100