apiVersion: apps/v1
kind: Deployment
metadata:
  name: logger-service
  namespace: pilot
  labels:
    app: logger-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: logger-service
  template:
    metadata:
      labels:
        app: logger-service
    spec:
      containers:
      - name: logger-service
        image: doldoleo/logger-service:latest
        ports:
        - containerPort: 8080
