spring:
  config:
    activate:
      on-profile: dev          
  cloud:
    openfeign:
      circuitbreaker:
         enabled: true
      client:
        config:
          user: # UserServiceOpenFeign.java 에서 선언된 feign client name
            url: http://user-service.pilot.svc.cluster.local
            connectTimeout: 3000
            readTimeout: 3000
            loggerLevel: FULL
          payment:
            url: http://payment-service.pilot.svc.cluster.local
            connectTimeout: 3000
            readTimeout: 3000
            loggerLevel: FULL
          default:
            connectTimeout: 3000
            readTimeout: 3000   
          