spring:
  config:
    activate:
      on-profile: local  
              
  security:
     oauth2:
        resourceserver:
           jwt:
              issuer-uri: http://localhost:9000  #인증에 필요한 jwt 토큰을 제공해주는 서버
        client:
           registration:
              komsco:
                 authorization-grant-type: client_credentials
                 client-id: swagger
                 client-secret: 1234
           provider: 
              komsco: # 조폐공사 Provider 등록!
                  token-uri: http://localhost:9000/oauth2/token #http://192.168.0.101:9000/oauth2/token

  cloud:
    openfeign:
      oauth2:
        enabled: true
        clientRegistrationId: komsco
      circuitbreaker:
         enabled: true
      client:
        config:
          user: # UserServiceOpenFeign.java 에서 선언된 feign client name
            url: http://localhost:8082
            connectTimeout: 3000
            readTimeout: 3000
            loggerLevel: FULL
          payment:
            url: http://localhost:8081
            connectTimeout: 3000
            readTimeout: 3000
            loggerLevel: FULL
          default:
            connectTimeout: 3000
            readTimeout: 3000             