spring:
  config:
    activate:
      on-profile: local          
  cloud:
    openfeign:
      circuitbreaker:
         enabled: true
      client:
        config:
          user: # UserServiceOpenFeign.java 에서 선언된 feign client name
            url: http://localhost:8082
            connectTimeout: 3000
            readTimeout: 3000
            loggerLevel: FULL
          payment:
            url: http://localhost:8081
            connectTimeout: 3000
            readTimeout: 3000
            loggerLevel: FULL
          default:
            connectTimeout: 3000
            readTimeout: 3000   
          