spring:
  config:
    activate:
      on-profile: common   # application-common.yaml 과 동일한 역할
  application:
      name: feign-service

resilience4j:
  circuitbreaker:
    configs:
      default:
        slidingWindowType: COUNT_BASED
        slidingWindowSize: 3
        minimumNumberOfCalls: 3
        permittedNumberOfCallsInHalfOpenState: 3 
        waitDurationInOpenState: 30s # HALF_OPEN 상태로 빨리 전환되어 장애가 복구 될 수 있도록 기본값(60s)보다 작게 설정
        #slowCallRateThreshold: 80 # slowCall 발생 시 서버 스레드 점유로 인해 장애가 생길 수 있으므로 기본값(100)보다 조금 작게 설정
        slowCallDurationThreshold: 5s # 위와 같은 이유로 5초를 slowCall로 판단함. 해당 값은 TimeLimiter의 timeoutDuration보다 작아야 함
        registerHealthIndicator: true
        recordFailurePredicate: openfeign.circuit.DefaultExceptionRecordFailurePredicate
    instances:
      default:
        baseConfig: default
  timelimiter:
    configs:
      default:
        timeoutDuration: 5s # slowCallDurationThreshold보다는 크게 설정되어야 함
        cancelRunningFuture: true
      
server:
  port: 9090     
   
#Actuator
management:
  endpoints:
    web:
      exposure:
        include: ["health", "info", "hystrix.stream"]
  endpoint:
    health:
      show-details: always
  tracing:
    sampling:
      probability: 1.0
    propagation:
      consume: B3
      produce: B3_MULTI
    enabled: true
  zipkin:
    tracing:
       endpoint: http://192.168.0.101:30411/api/v2/spans   
       
logging:
  level:
    feign:
      service: DEBUG
    openfeign: DEBUG

# HTML 형식의 swagger 문서의 사용자 경로 지정
springdoc:
  api-docs:
    path: /api/v1/merge/api-docs # 전체 API 정보를 가져오는 REST API
  packages-to-scan: feign.service   #api가 정의된 package 검색경로
  default-consumes-media-type: application/json;charset=UTF-8
  default-produces-media-type: application/json;charset=UTF-8  
  swagger-ui:
    operations-sorter: method  # delete - get - patch - post - put 순으로 정렬, alpha를 사용하면 알파벳 순으로 정렬 가능
    tags-sorter: alpha # 태그를 알파벳 순으로 정렬
    groups-order: DESC # path, query, body, response 순으로 출력
    disable-swagger-default-url: true
    #path: /swagger-ui.html  # swagger-ui 접근 경로에 대한 별칭, 해당 주소로 접속해도 http://localhost:8080/swagger-ui/index.html로 리다이렉션 됨.
    doc-expansion: none  
  paths-to-match:
    - /** # swagger-ui에 표시할 api의 엔드포인트 패턴   