apiVersion: v1
kind: Service
metadata:
  name: feign-service
  namespace: pilot
  labels:
    app: feign-service
spec:
  selector:
    app: feign-service
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 80
      targetPort: 9090