server:
   port: 8090

spring:  
   application:   
      name: config-service
   profiles:
      active: local
   
   config:
      import: optional:configserver:http://localhost:8888
#       import: "optional:configserver:"
#   cloud:
#      config:
#        uri: http://localhost:8888/
#        name: config-service
   cloud:
      config:
        enabled: false       
    
info:
  app:
    name: User Service
    description: 회원관리 서비스 제공

# config server actuator
management:
  endpoints:
    web:
       exposure:
         include: "*" #/actuator/refresh endpoint를 노출 시켜, 클라이언트의 context refresh를 실행시키도록 합니다.context refresh가 실행되면 config server로 부터 현재 프로퍼티 정보를 받아옵니다.
                      # - "refresh" # 위 '*'  으로 전체를 공개 해서 주석
                      # - "bus-refresh" # 위 '*'  으로 전체를 공개 해서 주석
       
# HTML 형식의 swagger 문서의 사용자 경로 지정
springdoc:
  api-docs:
    path: /api-docs/user # 전체 API 정보를 가져오는 REST API
  packages-to-scan: com.example.demo   #api가 정의된 package 검색경로
  default-consumes-media-type: application/json;charset=UTF-8
  default-produces-media-type: application/json;charset=UTF-8  
  swagger-ui:
    operations-sorter: method  # delete - get - patch - post - put 순으로 정렬, alpha를 사용하면 알파벳 순으로 정렬 가능
    tags-sorter: alpha # 태그를 알파벳 순으로 정렬
    groups-order: DESC # path, query, body, response 순으로 출력
    disable-swagger-default-url: true
    #path: /swagger-ui.html  # swagger-ui 접근 경로에 대한 별칭, 해당 주소로 접속해도 http://localhost:8080/swagger-ui/index.html로 리다이렉션 됨.
    doc-expansion: none  
  paths-to-match:
    - /** # swagger-ui에 표시할 api의 엔드포인트 패턴    
  
---
spring:
  config:
     activate:
        on-profile: local
config-service:
  profile: "local_2"
  region: "test_2"
          
---
spring:
  config:
     activate:
        on-profile: dev
config-service:
  profile: "dev"
  region: "test"