server:
  port: 9999

spring:
  application:
    name: swagger-gateway #MSA에서 해당 서비스를 구별할 수 있는 고유한 ID
  main:
    web-application-type: reactive    
  cloud:
    gateway:
      globalcors:
        add-to-simple-url-handler-mapping: true
      routes: #라우팅 규칙 목록 설정
        - id : payment-service
          uri: http://payment-service.pilot #http://payment-service.pilot #http://localhost:8000 OR lb://USER-SERVICE
          predicates:
            - Path=/api/v1/payment/**
            - Method=GET,POST,PUT,DELETE,OPTIONS
        - id : user-service
          uri: http://user-service.pilot #http://payment-service.pilot #http://localhost:8000 OR lb://USER-SERVICE
          predicates:
            - Path=/api/v1/user/**
            - Method=GET,POST,PUT,DELETE,OPTIONS    
        - id : feign-service
          uri: http://feign-service.pilot #http://payment-service.pilot #http://localhost:8000 OR lb://USER-SERVICE
          predicates:
            - Path=/api/v1/merge/**
            - Method=GET,POST,PUT,DELETE,OPTIONS         
management:
  endpoints:
    web:
      exposure:
        include: "*"
          
  endpoint:
    gateway:
      enabled: true  # default: true    
 
springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    use-root-path: true
    enabled: true
    #path: /swagger-ui/index.html
    config-url: /v3/api-docs/swagger-config
    urls:
       - url: /api/v1/payment/api-docs
         name: 지급결제 서비스  
       - url: /api/v1/user/api-docs
         name: 회원 서비스  
       - url: /api/v1/merge/api-docs
         name: 복합 서비스    
    urls-primary-name: Gateway  