server:
  port: 9999

spring:
  application:
    name: swagger-gateway #MSA에서 해당 서비스를 구별할 수 있는 고유한 ID
  profiles:
    active: local 

  main:
    web-application-type: reactive    
        
management:
  endpoints:
    web:
      exposure:
        include: "*"
          
  endpoint:
    gateway:
      enabled: true  # default: true    
 
springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    use-root-path: true
    enabled: true
    #path: /swagger-ui/index.html
    config-url: /v3/api-docs/swagger-config
    urls:
       - url: /api-docs/payment
         name: 지급결제 서비스  
       - url: /api-docs/user
         name: 회원 서비스  
       - url: /api-docs/merge
         name: 결합 서비스  
    urls-primary-name: Gateway  
    
---
spring:
  config:
     activate:
        on-profile: local
  cloud:
    gateway:
      globalcors:
        add-to-simple-url-handler-mapping: true
      routes: #라우팅 규칙 목록 설정
        - id : payment-service
          uri: http://localhost:8081 #lb://USER-SERVICE
          predicates:
            - Path=/api/v1/payment/**
            - Method=GET,POST,PUT,DELETE,OPTIONS
        - id : payment-service-api-docs
          uri: http://localhost:8081 #lb://USER-SERVICE
          predicates:
            - Path=/api-docs/payment
            - Method=GET    
        - id : user-service
          uri: http://localhost:8082 #lb://USER-SERVICE
          predicates:
            - Path=/api/v1/user/**
            - Method=GET,POST,PUT,DELETE,OPTIONS  
        - id : user-service-api-docs
          uri: http://localhost:8082 #lb://USER-SERVICE
          predicates:
            - Path=/api-docs/user/**
            - Method=GET    
        - id : feign-service-api-docs
          uri: http://localhost:9090 #lb://FEIGN-SERVICE
          predicates:
            - Path=/api-docs/merge/**
            - Method=GET    
        - id : feign-service
          uri: http://localhost:9090 #lb://FEIGN-SERVICE
          predicates:
            - Path=/api/v1/merge/**
            - Method=GET,POST,PUT,DELETE,OPTIONS    
---
spring:
  config:
     activate:
        on-profile: dev
  cloud:
    gateway:
      globalcors:
        add-to-simple-url-handler-mapping: true
      routes: #라우팅 규칙 목록 설정
        - id : payment-service-api-docs
          uri: http://payment-service.pilot #http://payment-service.pilot #http://localhost:8000 OR lb://USER-SERVICE
          predicates:
            - Path=/api-docs/payment
            - Method=GET
        - id : payment-service
          uri: http://payment-service.pilot #http://payment-service.pilot #http://localhost:8000 OR lb://USER-SERVICE
          predicates:
            - Path=/api/v1/payment/**
            - Method=GET,POST,PUT,DELETE,OPTIONS
        - id : user-service
          uri: http://user-service.pilot #http://payment-service.pilot #http://localhost:8000 OR lb://USER-SERVICE
          predicates:
            - Path=/api/v1/user/**
            - Method=GET,POST,PUT,DELETE,OPTIONS 
        - id : user-service-api-docs
          uri: http://user-service.pilot #http://payment-service.pilot #http://localhost:8000 OR lb://USER-SERVICE
          predicates:
            - Path=/api-docs/user
            - Method=GET     
        - id : feign-service-api-docs
          uri: http://feign-service.pilot #lb://FEIGN-SERVICE
          predicates:
            - Path=/api-docs/merge/**
            - Method=GET    
        - id : feign-service
          uri: http://feign-service.pilot #http://payment-service.pilot #http://localhost:8000 OR lb://USER-SERVICE
          predicates:
            - Path=/api/v1/merge/**
            - Method=GET,POST,PUT,DELETE,OPTIONS  